In [2]:
import numpy as np

def pivoteamentoParcial(A, k, i):

  n = np.shape(A)[0] - 1 #último index

  #slicing

  #Localizando o  maior valor na coluna do pivô, depois do pivô
  col = A[ i : n + 1, k ]

  colAbs = np.abs( col )

  indexMax = np.argmax( colAbs )


  #Trocando a coluna
  iChange = indexMax + i
  #print( ,iChange )

  aux = np.copy( A[ k, : ] )
  #print( aux )

  A[ k, : ] = np.copy( A[ iChange, : ] )
  A[ iChange, : ] = np.copy( aux )


  return A


U = np.array([[3.,(-4.),(1.)], [1.,2.,(2.)], [(4.),(0),(-3.)]])
#b = np.array([1.,2.,3.])
#L = np.zeros([3,3])

print("matriz exemplo")
print(U)
L = np.identity(len(U))
P = np.identity(3)

def FatoracaoLU(U,I):
    n = len(U)
    m = n*[0]
    
    for k in range(0,n):
        
        for i in range(k+1,n):
            print("k,i",k,i)
            U = pivoteamentoParcial(U,k,i)
            I = pivoteamentoParcial(I,k,i)
            m=U[i][k]/U[k][k]
            U[i][k] = 0
            L[i][k] = m
    
            for j in range(k+1,n):
                U[i][j] = U[i][j] - m*U[k][j]
    print(" ")
    print(I)
    print(" ")
    return L, U
                


FatoracaoLU(U,P)

print("Matriz L")
print(L)
print("        ")
print("Matriz U")
print(U)
print("        ")
#print("Multiplicacao de L por U")
#LU = np.dot(L,U)
#print(LU)

matriz exemplo
[[ 3. -4.  1.]
 [ 1.  2.  2.]
 [ 4.  0. -3.]]
k,i 0 1
k,i 0 2
k,i 1 2
 
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
 
Matriz L
[[1.         0.         0.        ]
 [0.25       1.         0.        ]
 [1.33333333 0.375      1.        ]]
        
Matriz U
[[ 3.         -4.          1.        ]
 [ 0.          5.33333333 -4.33333333]
 [ 0.          0.          4.375     ]]
        


In [3]:
#https://en.wikipedia.org/wiki/Gaussian_elimination (Fazer o exemplo e dizer por que não funciona)
M = np.array([[2.,1.,-1.],[-3.,-1.,2.],[-2.,1.,2.]])
b = np.array([[8.],[-11.],[-3.]])

print("matriz exemplo")
print(M)

def eliminacao(a,b):
    n = len(a)
    m = n*[0]
    if(np.linalg.det(a)==0):
        return print("o DETERMINANTE E ZERO")
    else:
        for k in range(0,n-1):
            for i in range(k+1,n):
                if a[k][k] == 0:
                    print("ERRO: PIVÔ IGUAL A ZERO")
                m=a[i][k]/a[k][k]
                if a[i][k] == 0:
                    continue
                a[i][k] = 0
                for j in range(k+1,n):
                    a[i][j] = a[i][j] - m*a[k][j]
                    b[i] = b[i] - m*b[k]
    print (a)

eliminacao(M,b)
print(b)

matriz exemplo
[[ 2.  1. -1.]
 [-3. -1.  2.]
 [-2.  1.  2.]]
[[ 2.   1.  -1. ]
 [ 0.   0.5  0.5]
 [ 0.   0.  -1. ]]
[[  8.]
 [ 13.]
 [-39.]]


In [4]:
#Adicionando melhorias ao código

In [5]:
import numpy as np
M = np.array([[1,-1,2],[2,1,-1],[-2,-5,3]])
b = np.array([[2],[1],[3]])

print("matriz exemplo")
print(M)

def eliminacao(a,b):
    n = len(a)
    m = n*[0]
    
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[k][k] == 0:
                print("ERRO: PIVÔ IGUAL A ZERO")
            m=a[i][k]/a[k][k]
            if a[i][k] == 0:
                continue
            a[i][k] = 0
            for j in range(k+1,n):
                a[i][j] = a[i][j] - m*a[k][j]
                b[i] = b[i] - m*b[k]
    return a
                


eliminacao(M,b)
print(b)

matriz exemplo
[[ 1 -1  2]
 [ 2  1 -1]
 [-2 -5  3]]
[[ 2]
 [-7]
 [-5]]


In [6]:
import numpy as np
M = np.array([[1,-1,2],[2,1,-1],[-2,-5,3]])
b = np.array([[2],[1],[3]])

print("matriz exemplo")
print(M)

def eliminacao(a,b):
    n = len(a)
    m = n*[0]
    if(np.linalg.det(a)==0):
        return print("o DETERMINANTE E ZERO")
    else:
        for k in range(0,n-1):
            for i in range(k+1,n):
                if a[k][k] == 0:
                    print("ERRO: PIVÔ IGUAL A ZERO")
                m=a[i][k]/a[k][k]
                if a[i][k] == 0:
                    continue
                a[i][k] = 0
                for j in range(k+1,n):
                    a[i][j] = a[i][j] - m*a[k][j]
                    b[i] = b[i] - m*b[k]
    return a
                


eliminacao(M,b)
print(b)

matriz exemplo
[[ 1 -1  2]
 [ 2  1 -1]
 [-2 -5  3]]
[[ 2]
 [-7]
 [-5]]


In [7]:
#Inserir o codigo de piv parcial na função de resolução de sistema triangular

In [8]:
#colocar esse código dentro do de resolução de sistema triangular
#Pivoteamento parcial

Amat  = np.matrix([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])
Aarr  = np.array([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])


A = Amat
print(A)

k = 1
i = 2
n = np.shape(A)[0] - 1#último index
print('n ', n, '\n')

#slicing
#Pegando a parte que ta abaixo do pivô
print( np.array( A[ i : n + 1, k ] ) )

#Localizando o  maior valor na coluna do pivô, depois do pivô
col = A[ i : n + 1, k ]

colAbs = np.abs( col )
print( 'colAbs \n', colAbs )

#Retorna o index do valor máximo
indexMax = np.argmax( colAbs )
print( indexMax )


#Trocando a coluna
iChange = indexMax + i
print( iChange )

aux = np.copy( A[ k, : ] )
print( aux )

#trocando a linha
A[ k, : ] = np.copy( A[ iChange, : ] )
A[ iChange, : ] = np.copy( aux )

print(A)

[[ 3  2  4 -1]
 [ 0  1  0  3]
 [ 0 -3 -5  7]
 [ 0  2  4  0]]
n  3 

[[-3]
 [ 2]]
colAbs 
 [[3]
 [2]]
0
2
[[0 1 0 3]]
[[ 3  2  4 -1]
 [ 0 -3 -5  7]
 [ 0  1  0  3]
 [ 0  2  4  0]]


In [9]:
import numpy as np

def pivoteamentoParcial(A, k, i):

  n = np.shape(A)[0] - 1 #último index
  print('n Ultimo ', n, '\n')

  #slicing
  print( np.array( A[ i : n + 1, k ] ) )

  #Localizando o  maior valor na coluna do pivô, depois do pivô
  col = A[ i : n + 1, k ]

  colAbs = np.abs( col )
  print( 'colAbs \n', colAbs )

  indexMax = np.argmax( colAbs )
  print( indexMax )


  #Trocando a coluna
  iChange = indexMax + i
  #print( ,iChange )

  aux = np.copy( A[ k, : ] )
  #print( aux )

  A[ k, : ] = np.copy( A[ iChange, : ] )
  A[ iChange, : ] = np.copy( aux )

  print(A)

  return A



def eliminacaoDegauss( A, b, n ): #Linha do pivô
    for k in np.arange( 1, n ): #
        print('k ', k)
        for i in np.arange( k + 1, n + 1 ): #Eliminação em cada linha
            print('i', i )
            A = pivoteamentoParcial(A,k,i) 
            m = A[ i, k ] / A[ k, k ] #Se for considerada divisão de inteiros dará zero
            print('m ', m) 
            A[ i, k ] = 0
            for j in np.arange( k + 1, n + 1 ):
                print('j', j )
        
    return A




b = np.array( [ 5, 6., 7., 15. ] )

Amat  = np.matrix([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])

A = Amat
print(A)

n = np.shape(A)[0] - 1#último index
print('n ', n)

eliminacaoDegauss( np.copy( A ), np.copy( b ), n )

[[ 3  2  4 -1]
 [ 0  1  0  3]
 [ 0 -3 -5  7]
 [ 0  2  4  0]]
n  3
k  1
i 2
n Ultimo  3 

[-3  2]
colAbs 
 [3 2]
0
[[ 3  2  4 -1]
 [ 0 -3 -5  7]
 [ 0  1  0  3]
 [ 0  2  4  0]]
m  -0.3333333333333333
j 2
j 3
i 3
n Ultimo  3 

[2]
colAbs 
 [2]
0
[[ 3  2  4 -1]
 [ 0  2  4  0]
 [ 0  0  0  3]
 [ 0 -3 -5  7]]
m  -1.5
j 2
j 3
k  2
i 3
n Ultimo  3 

[-5]
colAbs 
 [5]
0
[[ 3  2  4 -1]
 [ 0  2  4  0]
 [ 0  0 -5  7]
 [ 0  0  0  3]]
m  -0.0
j 3


array([[ 3,  2,  4, -1],
       [ 0,  2,  4,  0],
       [ 0,  0, -5,  7],
       [ 0,  0,  0,  3]])

In [10]:

M = np.array([[0.0002, 2],[2,2]])
b = np.array([5, 6])
x = np.linalg.solve(M,b)
print(x)

[0.50005001 2.49994999]
